name: CI Build Waterfox

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WFX_RELEASE: 1

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3 python3-pip nasm patchelf zstd curl ruby-dev build-essential

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Bootstrap browser build deps
        run: |
          ./mach bootstrap --application-choice=browser

      - name: Download and extract Clang 19
        run: |
          mkdir -p $HOME/.mozbuild
          curl -L https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.cache.level-3.toolchains.v3.linux64-clang-19.latest/artifacts/public/build/clang.tar.zst -o clang.tar.zst
          tar -xvf clang.tar.zst -C $HOME/.mozbuild
          ln -sf $HOME/.mozbuild/clang .mozconfig

      - name: Generate PGO profile
        env:
          GEN_PGO: 1
        run: |
          ./mach build
          ./mach package

      - name: Run profile server
        run: |
          ./mach python build/pgo/profileserver.py --binary ./obj-*/dist/waterfox/waterfox &
          sleep 30
          kill %1

      - name: Build with PGO
        run: |
          ./mach clobber
          unset GEN_PGO
          export USE_PGO=1
          ./mach build
          ./mach package

      - name: Install FPM
        run: |
          sudo gem install --no-document fpm

      - name: Build deb package
        run: |
          VERSION=$(git rev-parse --short HEAD)
          fpm -s dir \
            -t deb \
            -n waterfox \
            -v "$VERSION" \
            --architecture amd64 \
            --description "Waterfox browser built by GitHub Actions" \
            --url "https://github.com/BrowserWorks/Waterfox" \
            --license "MPL-2.0" \
            --maintainer "Your Name <you@example.com>" \
            --prefix /opt/waterfox \
            obj-*/dist/waterfox/

      - name: Upload deb artifact
        uses: actions/upload-artifact@v3
        with:
          name: waterfox-deb
          path: waterfox_amd64.deb
